# Generated by Django 5.1.2 on 2024-11-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hash_code', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('PROFESSOR', 'Professor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'STUDENT'}, to='engine.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(related_name='subjects', to='engine.class')),
                ('professors', models.ManyToManyField(limit_choices_to={'role': 'PROFESSOR'}, to='engine.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('rooms', models.CharField(max_length=200)),
                ('allowed_classes', models.ManyToManyField(to='engine.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.subject')),
            ],
        ),
    ]
